#!/usr/bin/env bash
# Copyright 2023-2024 GlitchyByte
# SPDX-License-Identifier: MIT

# Build Zappy.

# [Setup]
set -u # Exit with an error if a variable is used without being set.
set -e # Exit if any command returns an error.
# Capture caller directory and script directory.
readonly calling_dir="${PWD}"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"

# [Main]
if [ -d "dist" ]; then
  rm -dr dist
fi
find . -name ".DS_Store" -type f -delete
npm run build

# [Teardown]
cd "${calling_dir}"
