#!/usr/bin/env bash
# Copyright 2023-2024 GlitchyByte
# SPDX-License-Identifier: MIT

# Setup Zappy.

# [Setup]
set -u # Exit with an error if a variable is used without being set.
set -e # Exit if any command returns an error.
# Capture caller directory and script directory.
readonly calling_dir="${PWD}"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"

# [Main]
# Remove node_modules.
if [ -d "node_modules" ]; then
  rm -dr node_modules
fi
# Remove package-lock.json.
if [ -f "package-lock.json" ]; then
  rm package-lock.json
fi
# Install.
npm install

# [Teardown]
cd "${calling_dir}"
